export const elements = {
   selectedImage: document.querySelector('#selected-image'),
   imageName: document.querySelector('#image-name'),
   leftArrow: document.querySelector('#left-arrow'),
   rightArrow: document.querySelector('#right-arrow'),
   thumbnails: document.querySelectorAll('.thumbnail'),
   nextBee: document.querySelector('#next-bee'),
   prevBee: document.querySelector('#prev-bee'),
   beeThumbnails: document.querySelectorAll('.bee-thumbnail'),
   selectedBee: document.querySelector('#selected-bee'),
   beeName: document.querySelector('#bee-name'),
   calc: document.querySelector("input[value='calculate']"),
   male: document.querySelector("input[value='male']"),
   female: document.querySelector("input[value='female']"),
   reset: document.querySelector("input[value='reset']"),
   result: document.querySelector('#result'),
   weight: document.querySelector('#weight'),
   height: document.querySelector('#height'),
   age: document.querySelector('#age'),
   // anchor: document.querySelector("a[href^='#']"),
};
